Write errors to stderr
This will make the client display the error message from the server
instead of failing with a protocol violation error.

diff --git a/fugit b/fugit
--- a/fugit
+++ b/fugit
@@ -12,7 +12,7 @@ CONF=$CONFFILE
 contains_confdir(){
 	if [ ! -r "$1" ]; then
 		printf "%s %s: Cannot read config file, abort (Path %s)\n" "$(date)" "$2" "$1" >> $LOGFILE
-		printf "FAIL"
+		printf "FAIL\n" >&2
 		exit 24
 	fi
 	grep --fixed-strings --silent --line-regexp "$2" "$1"
@@ -49,7 +49,7 @@ check_acl(){
 			eval $(cat "$CONF/$REPONAME.conf")
 		else
 			printf "%s %s: Cannot read repo config, abort (Path %s)\n" "$(date)" "$3" "$CONF/$REPONAME.conf" >> $LOGFILE
-			printf "FAIL"
+			printf "FAIL\n" >&2
 			exit 23
 		fi
 		if [ "$1" == "pull" ]; then
@@ -84,7 +84,7 @@ push(){
 	printf "%s %s: Trying to push to %s (Path %s)\n" "$(date)" "$FUGIT_USER" "$1" "$REAL" >> $LOGFILE
 	if [ -z "$REAL" ]; then
 		printf "%s %s: Unknown repo, abort\n" "$(date)" "$FUGIT_USER" >> $LOGFILE
-		printf "ERR No such repository"
+		printf "ERR No such repository\n" >&2
 		return 1
 	fi
 
@@ -94,7 +94,7 @@ push(){
 		printf "%s %s: Push accepted\n" "$(date)" "$FUGIT_USER" >> $LOGFILE
 	else
 		printf "%s %s: Push rejected\n" "$(date)" "$FUGIT_USER" >> $LOGFILE
-		printf "ERR Access not permitted"
+		printf "ERR Access not permitted\n" >&2
 	fi
 }
 
@@ -105,7 +105,7 @@ pull(){
 	printf "%s %s: Trying to read from %s (Path %s)\n" "$(date)" "$FUGIT_USER" "$1" "$REAL" >> $LOGFILE
 	if [ -z "$REAL" ]; then
 		printf "%s %s: Unknown repo, abort\n" "$(date)" "$FUGIT_USER" >> $LOGFILE
-		printf "ERR No such repository"
+		printf "ERR No such repository\n" >&2
 		return 1
 	fi
 
@@ -115,7 +115,7 @@ pull(){
 		printf "%s %s: Pull accepted\n" "$(date)" "$FUGIT_USER" >> $LOGFILE
 	else
 		printf "%s %s: Pull rejected\n" "$(date)" "$FUGIT_USER" >> $LOGFILE
-		printf "ERR Access not permitted"
+		printf "ERR Access not permitted\n" >&2
 	fi
 }
 
